POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Bella",
  "password": "test"
}

###

# @name getUser
GET http://localhost:3000/users

###

POST http://localhost:3000/game_results
Content-Type: application/json

{
  "user_id": 3,
  "score": 35,
  "game_time": 199
}

###

# @name getgame_results
GET http://localhost:3000/game_results
Content-Type: application/json

###