# @name CreateUser
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "Johanna",
  "password": "test"
}

###

# @name LoginUser
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"name": "Bobo",
"password": "test"
}

###

# @name getUser
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJCb2JvIiwiaWF0IjoxNzM3MzU3MTM5fQ.iKEwqDufagY3PDfDpMMvbjJD6MzWk1xUtfw_Nyc3DTU

###

DELETE http://localhost:3000/user/17

###

# @name postGame_results
POST http://localhost:3000/game_results/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJCb2JvIiwiaWF0IjoxNzM3MzU3MTM5fQ.iKEwqDufagY3PDfDpMMvbjJD6MzWk1xUtfw_Nyc3DTU
Content-Type: application/json

{
  "user_id": 12,
  "total_score": 20
}

###

# @name getgame_results
GET http://localhost:3000/game_results/5
Content-Type: application/json

###