# @name CreateUser
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "Nanna2",
  "password": "test2"
}

###

# @name LoginUser
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"name": "Bobo",
"password": "test"
}

###

# @name getUser
GET http://localhost:3000/users

###

# @name postGame_results
POST http://localhost:3000/game_results
Content-Type: application/json

{
  "user_id": 3,
  "score": 35,
  "game_time": 199
}

###

# @name getgame_results
GET http://localhost:3000/game_results
Content-Type: application/json

###